sanger/aker-work-app

app/controllers/orders_controller.rb
app/models/work_order.rb
app/views/application/_products.html.erb
app/views/application/_total_cost.html.erb
app/views/orders/cost.html.erb
app/views/orders/set.html.erb
app/views/orders/summary.html.erb
app/views/work_orders/show.html.erb

1. Create the locked set before calculating the total cost.
2. Don't ever try and create the locked set twice.
3. Don't let the user change the selected set once the locked
set has been created.
4. Show total cost on the summary page.

Making the wizard back-and-forward proof

---

app/controllers/orders_controller.rb
app/controllers/work_orders_controller.rb
app/views/orders/_buttons.html.erb

A work order completed
may not be deleted,
and once fully stated
should not be updated.

Block updating or deleting a work order that has already been issued.

---

app/controllers/orders_controller.rb

Requires functionality currently on authorisation branch of set service

Only show sets belonging to current user

---

app/controllers/orders_controller.rb
app/models/work_order.rb
app/services/update_order_service.rb
db/migrate/20170511150048_add_total_cost_to_work_order.rb
db/schema.rb
spec/factories/products.rb
spec/factories/work_orders.rb
spec/models/catalogue_spec.rb
spec/models/product_spec.rb
spec/models/user_spec.rb
spec/models/work_order_spec.rb
spec/services/update_order_service_spec.rb

Refactored the big perform_step function from OrdersController 
into its own class, UpdateOrderService

Improvements for the work orders service

---

spec/lib/event_message_spec.rb

fixed test for event message which now includes product and proposal role

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/controllers/orders_controller.rb
app/views/orders/set.html.erb

jQuery is used to allow clicking the whole row to select a radio button. I've added a column to show the time since each set was created.

A131 - Sort sets by newest first

---

Gemfile.lock

Already merged devel into move_cost_info as there was complex conficts to be resolved
So minor commit to show difference

Merge move_cost_info into devel

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb

Show env in navbar and change colour based on environment

---

app/views/application/_sets.html.erb
features/step_definitions/basic_definitions.rb
spec/lib/event_publisher_spec.rb

Display and explain locked and original input sets

---

app/views/application/_sets.html.erb

* Fix "Order Work" button display conditions and set ID
* Open button links in new tabs

Merge devel into staging

---

Gemfile
Gemfile.lock
app/models/work_order.rb
spec/models/work_order_spec.rb
spec/support/test_services_helper.rb

This depends on the changes in the study application, and on the study client (https://github.com/sanger/aker-study-client/pull/5)

A188 - send data_release_uuid with release json

---

app/controllers/products_controller.rb
app/helpers/orders_helper.rb
app/javascript/components/product_description.jsx
app/models/aker/process.rb
app/models/catalogue.rb
app/models/product.rb
app/views/application/_accordion_body.html.erb
config/locales/en.yml
db/migrate/20180316152215_move_product_class_to_process.rb
db/schema.rb
messages.md
spec/controllers/products_controller_spec.rb
spec/models/aker/process_spec.rb
spec/models/catalogue_spec.rb
spec/models/product_spec.rb

Removed product.product_class and replaced with process.process_class

Process class

---

app/models/job.rb
spec/models/job_spec.rb

jobs_spec should be job_spec
Job.status was needlessly confusing.
Job.status_ready_for_update did not work.

code review edits

---

app/services/completion_cancel_steps/update_work_order_step.rb
spec/requests/api/v1/jobs_spec.rb
spec/services/completion_cancel_steps/update_work_order_step_spec.rb

make sure the work order can only be updated in a way that makes sense

suggested edit for update_work_order_step

---

app/models/work_plan.rb
app/services/update_plan_service.rb
spec/models/work_plan_spec.rb
spec/services/update_plan_service_spec.rb

before the project data_release_uuid was checked to exist

Fixed a bug where jobs were being created

---

app/models/job.rb
app/models/work_order.rb
app/services/update_plan_service.rb
spec/models/job_spec.rb
spec/models/work_order_spec.rb

Send multiple jobs to the lims in a single message

---

app/views/plan_wizard/dispatch.html.erb

Add extra info and tidy layout of Work Plan summary

---

app/models/work_order.rb
app/services/update_plan_service.rb
spec/models/work_order_spec.rb
spec/services/update_plan_service_spec.rb

rollback materials availability

Fix the rollback of send_to_lims when post fails

---

app/javascript/components/product_description.jsx

UX changes to ProductDescription JSX module

---

app/views/plan_wizard/dispatch.html.erb
config/environments/development.rb

Because that's where everywhere else is looking for it.

development.rb - connect to set service on 3000
